id = "slint"
name = "Slint"
version = "0.0.3"
schema_version = 1
description = "Slint support for Zed"
repository = "https://gitlab.com/flukejones/zed-slint"
authors = ["Luke. D Jones <luke@ljones.dev>"]
themes = []
languages = ["languages/slint"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.slint]
repository = "https://github.com/slint-ui/tree-sitter-slint.git"
rev = "acc77c93ef4b73ba8c3a581b8c99d95b55f7178b"

[language_servers.slint]
language = "Slint"
languages = []

[language_servers.slint.language_ids]
