id = "dart"
name = "Dart"
version = "0.2.0"
schema_version = 1
description = "Dart support."
repository = "https://github.com/zed-extensions/dart"
authors = ["Abdullah Alsigar <abdullah.alsigar@gmail.com>", "Flo <flo80@users.noreply.github.com>", "ybbond <hi@ybbond.id>", "nielsenko <kasper@byolimit.com>"]
themes = []
icon_themes = []
languages = ["languages/dart"]
capabilities = []

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.dart]
repository = "https://github.com/UserNobody14/tree-sitter-dart"
rev = "80e23c07b64494f7e21090bb3450223ef0b192f4"

[language_servers.dart]
language = "Dart"
languages = ["Dart"]

[language_servers.dart.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
