
$image = 
$background = rgba(131313ff)

$image = 
$error = rgba(ffb4abff)

$image = 
$error_container = rgba(93000aff)

$image = 
$inverse_on_surface = rgba(303030ff)

$image = 
$inverse_primary = rgba(586060ff)

$image = 
$inverse_surface = rgba(e5e2e1ff)

$image = 
$on_background = rgba(e5e2e1ff)

$image = 
$on_error = rgba(690005ff)

$image = 
$on_error_container = rgba(ffdad6ff)

$image = 
$on_primary = rgba(2a3232ff)

$image = 
$on_primary_container = rgba(a7afafff)

$image = 
$on_primary_fixed = rgba(151d1dff)

$image = 
$on_primary_fixed_variant = rgba(404848ff)

$image = 
$on_secondary = rgba(2e3131ff)

$image = 
$on_secondary_container = rgba(dfe0e0ff)

$image = 
$on_secondary_fixed = rgba(191c1cff)

$image = 
$on_secondary_fixed_variant = rgba(444747ff)

$image = 
$on_surface = rgba(e5e2e1ff)

$image = 
$on_surface_variant = rgba(c3c7c7ff)

$image = 
$on_tertiary = rgba(3a2e28ff)

$image = 
$on_tertiary_container = rgba(bcaaa2ff)

$image = 
$on_tertiary_fixed = rgba(241914ff)

$image = 
$on_tertiary_fixed_variant = rgba(51443eff)

$image = 
$outline = rgba(8d9291ff)

$image = 
$outline_variant = rgba(434847ff)

$image = 
$primary = rgba(c0c8c8ff)

$image = 
$primary_container = rgba(1c2424ff)

$image = 
$primary_fixed = rgba(dce4e4ff)

$image = 
$primary_fixed_dim = rgba(c0c8c8ff)

$image = 
$scrim = rgba(000000ff)

$image = 
$secondary = rgba(c5c7c6ff)

$image = 
$secondary_container = rgba(444747ff)

$image = 
$secondary_fixed = rgba(e1e3e2ff)

$image = 
$secondary_fixed_dim = rgba(c5c7c6ff)

$image = 
$shadow = rgba(000000ff)

$image = 
$source_color = rgba(1c2424ff)

$image = 
$surface = rgba(131313ff)

$image = 
$surface_bright = rgba(393939ff)

$image = 
$surface_container = rgba(1f201fff)

$image = 
$surface_container_high = rgba(2a2a2aff)

$image = 
$surface_container_highest = rgba(353534ff)

$image = 
$surface_container_low = rgba(1b1c1bff)

$image = 
$surface_container_lowest = rgba(0e0e0eff)

$image = 
$surface_dim = rgba(131313ff)

$image = 
$surface_tint = rgba(c0c8c8ff)

$image = 
$surface_variant = rgba(434847ff)

$image = 
$tertiary = rgba(d6c3bbff)

$image = 
$tertiary_container = rgba(2b201bff)

$image = 
$tertiary_fixed = rgba(f3ded6ff)

$image = 
$tertiary_fixed_dim = rgba(d6c3bbff)

